# Generated by Django 5.1 on 2024-09-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donar_model',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donar_model',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
