# Generated by Django 5.1 on 2024-09-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0002_alter_donar_model_medical_history_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donar_model',
            new_name='Donor_model',
        ),
    ]
