# Generated by Django 5.1 on 2024-09-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=10)),
                ('blood_units', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('reason', models.TextField()),
            ],
            options={
                'db_table': 'Patient_details_table',
            },
        ),
    ]
